name: build unity plugins

on: 
  workflow_dispatch:
  push:
    paths: 
      - unity/native_src/**
      - unity/native_src_ourv8/**
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.cpp
      - unreal/Puerts/Source/JsEnv/Private/V8InspectorImpl.h
      - unreal/Puerts/Source/JsEnv/Private/PromiseRejectCallback.hpp
      - .github/workflows/unity_build_plugins.yml

env:
  RUNID: 613573412

jobs:
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - name: Get backend artifact
        uses: ./.github/workflows/composites/unity-download-backend/
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backend: 'v8'
      - name: Build
        run: |
          cd unity\native_src
          .\make_win64.bat
          .\make_win32.bat
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          path: ./unity/Assets/Plugins/**/*
          name: Unity_Plugins_V8